import os
from huggingface_hub import HfApi, hf_hub_download
from huggingface_hub.utils import RepositoryNotFoundError

TOKEN = os.environ.get("HF_TOKEN", "")
api = HfApi(token=TOKEN)

def get_file(repo, filename, repo_type="dataset"):
    try:
        path = hf_hub_download(repo_id=repo, filename=filename, repo_type=repo_type, token=TOKEN)
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        return None

print("=== Modifying zcc-ir-prime-v1 ===")
ir_prime_card = """---
license: apache-2.0
language:
  - en
  - code
tags:
  - compiler
  - intermediate-representation
  - zcc
size_categories:
  - 1K<n<10K
---
# ZCC IR PRIME v1 Dataset

This dataset contains 1,449 function-level Intermediate Representation (IR) graphs generated by the Zkaedi C Compiler (ZCC), scored using autonomous PRIME Hamiltonian energy dynamics and semantic evaluations.

## Dataset Structure

Each row represents a single C function compiled to ZCC's 3-address SSA IR.

**Total records:** 1,449 functions
- `zcc-self-compile`: 177 functions (the ZCC compiler compiling itself)
- `libcurl-8.7.1`: 1,272 functions (ZCC compiling the libcurl network/IO library)

### Fields / Schema
- `id`: Unique identifier for the function.
- `source`: The origin codebase generating the IR (`zcc-self-compile` or `libcurl-8.7.1`).
- `function_name`: Name of the compiled C function.
- `ir_text`: The raw textual representation of the 3-address SSA IR.
- `prime_score` / `metrics`: Scoring matrices denoting the dataset's complexity and optimization load.
"""
api.upload_file(
    path_or_fileobj=ir_prime_card.encode("utf-8"),
    path_in_repo="README.md",
    repo_id="zkaedi/zcc-ir-prime-v1",
    repo_type="dataset"
)
print("Updated zcc-ir-prime-v1 README.md")

print("=== Modifying zcc-compiler-bug-corpus ===")
bug_corpus_readme = get_file("zkaedi/zcc-compiler-bug-corpus", "README.md", "dataset")
if bug_corpus_readme:
    # Update it if it exists. If we don't find it easily regexed, we will just print it and do it manually.
    if "7th stress category" not in bug_corpus_readme:
        print("Existing body found for bug corpus. Let's see it to understand where to insert:")
        print(bug_corpus_readme[:500])
        # fallback simple replacement or append
        new_readme = bug_corpus_readme + "\n\n### Network/IO Category\n- **libcurl-8.7.1** has been added as the 7th stress category, validating networking abstractions, complex `va_list` variadic architectures on SysV AMD64, global initializers, and deeply nested structs.\n"
        api.upload_file(
            path_or_fileobj=new_readme.encode("utf-8"),
            path_in_repo="README.md",
            repo_id="zkaedi/zcc-compiler-bug-corpus",
            repo_type="dataset"
        )
        print("Appended libcurl info to zcc-compiler-bug-corpus README.md")
else:
    # Fallback to creating a new one if it doesn't exist
    new_readme = """---
license: apache-2.0
---
# ZCC Compiler Bug Corpus

A growing dataset of confirmed, ground-truth C compiler codegen bugs, AST traversal faults, and SysV ABI violations discovered during the creation of the ZCC compiler.

## Provenance Codebases (Stress Categories)
1. Baseline Arithmetic
2. Memory Allocation
3. Complex Expressions
4. SQLite 3.45.0
5. DOOM 1.10
6. Lua 5.4.6
7. **libcurl-8.7.1** (Network/IO)
"""
    api.upload_file(
        path_or_fileobj=new_readme.encode("utf-8"),
        path_in_repo="README.md",
        repo_id="zkaedi/zcc-compiler-bug-corpus",
        repo_type="dataset"
    )
    print("Created new zcc-compiler-bug-corpus README.md")

print("=== Creating HF Profile (zkaedi/zkaedi) ===")
try:
    api.create_repo(repo_id="zkaedi/zkaedi", repo_type="model", exist_ok=True)
    profile_content = """# Zkaedi / Antigravity

Autonomous Systems Engineering Intelligence.

## Mandate
- Stabilization and development of C Compilers (ZCC), embedded game scripting logic, and JIT environments.
- Research into 3-address IR optimizations, memory alignment rules, and x86-64 System V AMD64 ABI compliances.
- Exploration of low-latency MEV engines and Hamiltonian topology mapping for vectorized embeddings.

## Key Projects
- **ZCC**: A fully self-hosting, optimizing C compiler targeting x86-64 Linux. Capable of compiling SQLite, DOOM, and libcurl.
- **Zkaedi Prime**: Autonomous AGI-driven audio-reactive visualizer mapping thousands of particles using recursive Hamiltonian physics.
- **Zkaedi Semantic Manifold**: Embedding visualizations and topology analysis for zero-knowledge insights.
"""
    api.upload_file(
        path_or_fileobj=profile_content.encode("utf-8"),
        path_in_repo="README.md",
        repo_id="zkaedi/zkaedi",
        repo_type="model"
    )
    print("Created zkaedi/zkaedi profile README")
except Exception as e:
    print(f"Error creating profile repo: {e}")

print("=== Cleaning Up Stale Repos ===")
repos_to_delete = ["meta-hamiltonian-benchmarkO", "zkaedi_ensamble"]
for r in repos_to_delete:
    full_r = f"zkaedi/{r}"
    for r_type in ["dataset", "model", "space"]:
        try:
            api.delete_repo(repo_id=full_r, repo_type=r_type)
            print(f"Deleted {full_r} ({r_type})")
            break
        except Exception as e:
            pass
print("Done.")
