#!/usr/bin/env python3
"""
multi_scene_extractor.py  —  Extract multiple Tripo LOD GLBs into a single
models.h for the ZCC multi-UFO raytracer scene.

Each mesh gets:
  - Its own triangle array (up to MAX_FACES triangles)
  - Per-triangle sampled texture color (via UV barycentric sampling)
  - An offset Vec3 so objects are spaced across the scene
  - AABB in world space (after offset)

Output: models.h with:
  int   SCENE_MESH_COUNT
  Mesh  scene_meshes[N]   where Mesh = {triangles, count, aabb_min, aabb_max}
"""
import sys, struct, numpy as np, trimesh
from PIL import Image
import io

MAX_FACES = 30000  # patched ZCC MAX_INIT can handle 131072, so 3x30000 = 90k is fine

SCENE = [
    # (filename,  world_offset_xyz,  fallback_rgb)
    ('lod_out/Heavy_Metal_Apocalypse_UFO_LOD1.glb',   (-2.8, 0.0,  0.0), (0.6, 0.55, 0.5)),
    ('lod_out/Ancient_Overgrown_Jungle_UFO_LOD1.glb', ( 0.0, 0.0,  0.0), (0.3, 0.6,  0.25)),
    ('lod_out/Kitsune_Anime_3D_LOD1.glb',             ( 2.8, 0.0,  0.0), (0.9, 0.4,  0.5)),
]

def sample_texture(mesh, face_indices):
    """Return (N,3) float rgb in [0,1] per face, sampled at face centroid UV."""
    try:
        mat = list(mesh.geometry.values())[0].visual.material
        tex = getattr(mat, 'baseColorTexture', None)
        if tex is None:
            raise ValueError('no texture')
        # trimesh returns a PIL Image directly
        if hasattr(tex, 'convert'):
            img = tex.convert('RGB')
        else:
            img = Image.open(io.BytesIO(tex)).convert('RGB')
        iw, ih = img.size
        arr = np.array(img, dtype=np.float32) / 255.0  # (H, W, 3)

        flat = trimesh.util.concatenate(list(mesh.geometry.values()))
        uvs = flat.visual.uv  # (V, 2)
        if uvs is None or len(uvs) == 0:
            raise ValueError('no uvs')

        # centroid UV per face
        f = flat.faces[face_indices]
        uv_face = uvs[f]               # (N, 3, 2)
        uv_c = uv_face.mean(axis=1)    # (N, 2) centroid

        px = np.clip((uv_c[:, 0] * iw).astype(int), 0, iw - 1)
        py = np.clip(((1.0 - uv_c[:, 1]) * ih).astype(int), 0, ih - 1)
        colors = arr[py, px]           # (N, 3)
        return colors
    except Exception as e:
        print(f'  [texture] fallback: {e}')
        return None


def load_mesh(glb_path, max_faces=MAX_FACES):
    scene  = trimesh.load(glb_path, force='scene')
    flat   = trimesh.util.concatenate(list(scene.geometry.values()))
    faces  = flat.faces
    verts  = flat.vertices

    # Subsample if needed
    if len(faces) > max_faces:
        idx = np.linspace(0, len(faces) - 1, max_faces, dtype=int)
        face_indices = idx
        faces = faces[idx]
    else:
        face_indices = np.arange(len(faces))

    # Normalise into [-1, 1]
    vmin = verts.min(0); vmax = verts.max(0)
    center = (vmin + vmax) / 2.0
    scale  = max(vmax - vmin) * 0.5
    if scale == 0: scale = 1.0
    verts = (verts - center) / scale

    # Texture colours
    colors = sample_texture(scene, face_indices)

    return faces, verts, colors


def fmt_v3(v, fallback=(1,1,1)):
    return f'{{{v[0]:.5f}, {v[1]:.5f}, {v[2]:.5f}}}'


def main():
    out_path = '/mnt/h/__DOWNLOADS/zcc_github_upload/models.h'
    base_dir = '/mnt/h/__DOWNLOADS/zcc_github_upload/'

    all_meshes = []
    for (glb_rel, offset, fallback_rgb) in SCENE:
        glb = base_dir + glb_rel
        print(f'Loading {glb_rel} ...')
        faces, verts, tex_colors = load_mesh(glb)
        all_meshes.append((faces, verts, tex_colors, offset, fallback_rgb))
        print(f'  {len(faces)} faces extracted')

    with open(out_path, 'w') as f:
        f.write('#ifndef MODELS_H\n#define MODELS_H\n\n')
        f.write('/* Auto-generated by multi_scene_extractor.py */\n\n')

        # Minimal type defs (matches raytracer.c)
        f.write('typedef struct { double x, y, z; } Vec3;\n')
        f.write('typedef struct { Vec3 v0, v1, v2; Vec3 color; double reflectivity; double shininess; } Triangle;\n')
        f.write('typedef struct {\n')
        f.write('    Triangle *tris; int count;\n')
        f.write('    Vec3 aabb_min, aabb_max;\n')
        f.write('} Mesh;\n\n')

        # Per-mesh triangle arrays
        for mi, (faces, verts, tex_colors, offset, fallback_rgb) in enumerate(all_meshes):
            ox, oy, oz = offset
            count = len(faces)
            f.write(f'Triangle mesh_tris_{mi}[{count}] = {{\n')
            for i, face in enumerate(faces):
                v0 = verts[face[0]] + np.array([ox, oy, oz])
                v1 = verts[face[1]] + np.array([ox, oy, oz])
                v2 = verts[face[2]] + np.array([ox, oy, oz])
                if tex_colors is not None:
                    r, g, b = tex_colors[i]
                else:
                    r, g, b = fallback_rgb
                # Clamp slightly so nothing goes full black
                r = max(r, 0.05); g = max(g, 0.05); b = max(b, 0.05)
                comma = ',' if i < count - 1 else ''
                f.write(f'  {{ {fmt_v3(v0)}, {fmt_v3(v1)}, {fmt_v3(v2)}, '
                        f'{{{r:.4f}, {g:.4f}, {b:.4f}}}, 0.08, 30.0 }}{comma}\n')
            f.write('};\n\n')

        # Mesh array + scene count
        n = len(all_meshes)
        f.write(f'int SCENE_MESH_COUNT = {n};\n\n')

        # Write per-mesh aabb (after offset applied)
        # Compute from verts+offset
        for mi, (faces, verts, tex_colors, offset, fallback_rgb) in enumerate(all_meshes):
            ox, oy, oz = offset
            sv = verts + np.array([ox, oy, oz])
            mn = sv.min(0); mx = sv.max(0)
            f.write(f'Vec3 aabb_min_{mi} = {fmt_v3(mn)};\n')
            f.write(f'Vec3 aabb_max_{mi} = {fmt_v3(mx)};\n')

        f.write('\n')
        f.write('/* Mesh table — must be after the triangle arrays */\n')
        f.write('Mesh scene_meshes[] = {\n')
        for mi in range(n):
            faces, verts, tex_colors, offset, fallback_rgb = all_meshes[mi]
            ox, oy, oz = offset
            sv = verts + np.array([ox, oy, oz])
            mn = sv.min(0); mx = sv.max(0)
            comma = ',' if mi < n - 1 else ''
            f.write(f'  {{ mesh_tris_{mi}, {len(faces)}, '
                    f'{fmt_v3(mn)}, {fmt_v3(mx)} }}{comma}\n')
        f.write('};\n\n')
        f.write('#endif\n')

    total = sum(len(m[0]) for m in all_meshes)
    print(f'\nWrote {out_path}  ({n} meshes, {total} total triangles)')

if __name__ == '__main__':
    main()
