import re
import sys

def parse_enums(filename):
    with open(filename, 'r') as f:
        content = f.read()

    match = re.search(r'/\* =+ \*/\s*/\* AST NODE TYPES\s*\*/\s*/\* =+ \*/\s*enum \{(.*?)\};', content, re.DOTALL)
    if not match:
        print("ERROR: AST node types enum not found in", filename)
        sys.exit(1)
    
    enum_body = match.group(1)
    parsed = {}
    current_val = 0
    
    enum_body = re.sub(r'/\*.*?\*/', '', enum_body, flags=re.DOTALL)
    enum_body = re.sub(r'//.*', '', enum_body)
    
    tokens = enum_body.split(',')
    for t in tokens:
        t = t.strip()
        if not t:
            continue
        if '=' in t:
            name, val = t.split('=')
            name = name.strip()
            val = val.strip()
            current_val = int(val)
            parsed[name] = current_val
            current_val += 1
        else:
            name = t.strip()
            parsed[name] = current_val
            current_val += 1
            
    return parsed

def generate_header(parsed, header_path, assert_path):
    # Constants file
    out = []
    out.append("/* Auto-generated by sync_bridge.py. DO NOT EDIT. */")
    out.append("#ifndef ZCC_AST_BRIDGE_CONSTANTS_H")
    out.append("#define ZCC_AST_BRIDGE_CONSTANTS_H\n")
    for name, val in parsed.items():
        if name.startswith("ND_"):
            out.append(f"#define ZCC_{name} {val}")
    out.append("\n#endif /* ZCC_AST_BRIDGE_CONSTANTS_H */")
    with open(header_path, 'w') as f:
        f.write("\n".join(out))

    # Asserts file
    out_assert = []
    out_assert.append("/* Auto-generated by sync_bridge.py. DO NOT EDIT. */")
    for name, val in parsed.items():
        if name.startswith("ND_"):
            out_assert.append(f"typedef char zcc_static_assert_{name}[ ({name} == ZCC_{name}) ? 1 : -1 ];")
    with open(assert_path, 'w') as f:
        f.write("\n".join(out_assert))

def main():
    if len(sys.argv) != 4:
        print("Usage: sync_bridge.py <part1.c> <constants.h> <asserts.inc>")
        sys.exit(1)
        
    part1_path = sys.argv[1]
    const_path = sys.argv[2]
    assert_path = sys.argv[3]
    
    parsed = parse_enums(part1_path)
    generate_header(parsed, const_path, assert_path)
    print(f"Successfully generated {const_path} and {assert_path} with {len(parsed)} AST node mappings.")

if __name__ == '__main__':
    main()
