typedef enum {
    E_NONE = 0,

    E_LAYOUT_ZERO_SIZE,
    E_LAYOUT_MISMATCH,
    E_LAYOUT_UNKNOWN_KIND,
    E_LAYOUT_RECURSIVE_TYPE,
    E_LAYOUT_INCOMPLETE_TYPE,
    E_LAYOUT_SIZE_OVERFLOW,
    E_LAYOUT_UNSUPPORTED_BITFIELD,
    E_LAYOUT_UNSUPPORTED_FLEXIBLE_ARRAY,

    E_STATIC_ASSERT_FAILED,
    E_STATIC_ASSERT_NOT_CONSTANT,

    E_ALIGNOF_TYPE,
    E_ALIGNAS_INVALID,
    E_TARGET_UNKNOWN
} ErrorCode;