/*
 *  TCC - Tiny C Compiler
 *
 *  Copyright (c) 2001-2004 Fabrice Bellard
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */





/* Automatically generated by configure - do not modify */












































typedef struct { unsigned int gp_offset; unsigned int fp_offset; void *overflow_arg_area; void *reg_save_area; } __va_list_struct[1];










typedef int int32_t;
typedef unsigned int uint32_t;
typedef long int64_t;
typedef unsigned long uint64_t;
typedef char int8_t;
typedef unsigned char uint8_t;
typedef short int16_t;
typedef unsigned short uint16_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef struct _IO_FILE FILE;
extern FILE *stdin, *stdout, *stderr;



























































































































































































































































































































































































































































































































































































































































































































/* XXX: need to define this to use them in non ISOC99 context */
extern float strtof (const char *__nptr, char **__endptr);
extern long double strtold (const char *__nptr, char **__endptr);


































































/* -------------------------------------------- */

/* parser debug */
/* #define PARSE_DEBUG */
/* preprocessor debug */
/* #define PP_DEBUG */
/* include file debug */
/* #define INC_DEBUG */
/* memory leak debug */
/* #define MEM_DEBUG */
/* assembler debug */
/* #define ASM_DEBUG */

/* target selection */
/* #define TCC_TARGET_I386   *//* i386 code generator */
/* #define TCC_TARGET_X86_64 *//* x86-64 code generator */
/* #define TCC_TARGET_ARM    *//* ARMv4 code generator */
/* #define TCC_TARGET_ARM64  *//* ARMv8 code generator */
/* #define TCC_TARGET_C67    *//* TMS320C67xx code generator */

/* default target is I386 */

















/* only native compiler supports -run */



















/* ------------ path configuration ------------ */


















/* path to find crt1.o, crti.o and crtn.o */




/* Below: {B} is substituted by CONFIG_TCCDIR (rsp. -B option) */

/* system include paths */








/* library search paths */








/* name of ELF interpreter */








































/* var elf_interp dans *-gen.c */






/* (target specific) libtcc1.a */




/* library to use with CONFIG_USE_LIBGCC instead of libtcc1.a */




/* -------------------------------------------- */












struct TCCState;

typedef struct TCCState TCCState;

/* create a new TCC compilation context */
 TCCState *tcc_new(void);

/* free a TCC compilation context */
 void tcc_delete(TCCState *s);

/* set CONFIG_TCCDIR at runtime */
 void tcc_set_lib_path(TCCState *s, const char *path);

/* set error/warning display callback */
 void tcc_set_error_func(TCCState *s, void *error_opaque,
    void (*error_func)(void *opaque, const char *msg));

/* set options as from command line (multiple supported) */
 void tcc_set_options(TCCState *s, const char *str);

/*****************************/
/* preprocessor */

/* add include path */
 int tcc_add_include_path(TCCState *s, const char *pathname);

/* add in system include path */
 int tcc_add_sysinclude_path(TCCState *s, const char *pathname);

/* define preprocessor symbol 'sym'. Can put optional value */
 void tcc_define_symbol(TCCState *s, const char *sym, const char *value);

/* undefine preprocess symbol 'sym' */
 void tcc_undefine_symbol(TCCState *s, const char *sym);

/*****************************/
/* compiling */

/* add a file (C file, dll, object, library, ld script). Return -1 if error. */
 int tcc_add_file(TCCState *s, const char *filename);

/* compile a string containing a C source. Return -1 if error. */
 int tcc_compile_string(TCCState *s, const char *buf);

/*****************************/
/* linking commands */

/* set output type. MUST BE CALLED before any compilation */
 int tcc_set_output_type(TCCState *s, int output_type);






/* equivalent to -Lpath option */
 int tcc_add_library_path(TCCState *s, const char *pathname);

/* the library name is the same as the argument of the '-l' option */
 int tcc_add_library(TCCState *s, const char *libraryname);

/* add a symbol to the compiled program */
 int tcc_add_symbol(TCCState *s, const char *name, const void *val);

/* output an executable, library or object file. DO NOT call
   tcc_relocate() before. */
 int tcc_output_file(TCCState *s, const char *filename);

/* link and run main() function and return its value. DO NOT call
   tcc_relocate() before. */
 int tcc_run(TCCState *s, int argc, char **argv);

/* do all relocations (needed before using tcc_get_symbol()) */
 int tcc_relocate(TCCState *s1, void *ptr);
/* possible values for 'ptr':
   - TCC_RELOCATE_AUTO : Allocate and manage memory internally
   - NULL              : return required memory size for the step below
   - memory address    : copy code to memory passed by the caller
   returns -1 if error. */


/* return symbol value or NULL if not found */
 void *tcc_get_symbol(TCCState *s, const char *name);







/* This file defines standard ELF types, structures, and macros.
   Copyright (C) 1995-2012 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */


















































































/* Standard ELF types.  */

/* Type for a 16-bit quantity.  */
typedef uint16_t Elf32_Half;
typedef uint16_t Elf64_Half;

/* Types for signed and unsigned 32-bit quantities.  */
typedef uint32_t Elf32_Word;
typedef	int32_t  Elf32_Sword;
typedef uint32_t Elf64_Word;
typedef	int32_t  Elf64_Sword;

/* Types for signed and unsigned 64-bit quantities.  */
typedef uint64_t Elf32_Xword;
typedef	int64_t  Elf32_Sxword;
typedef uint64_t Elf64_Xword;
typedef	int64_t  Elf64_Sxword;

/* Type of addresses.  */
typedef uint32_t Elf32_Addr;
typedef uint64_t Elf64_Addr;

/* Type of file offsets.  */
typedef uint32_t Elf32_Off;
typedef uint64_t Elf64_Off;

/* Type for section indices, which are 16-bit quantities.  */
typedef uint16_t Elf32_Section;
typedef uint16_t Elf64_Section;

/* Type for version symbol information.  */
typedef Elf32_Half Elf32_Versym;
typedef Elf64_Half Elf64_Versym;


/* The ELF file header.  This appears at the start of every ELF file.  */



typedef struct
{
  unsigned char	e_ident[(16)];	/* Magic number and other info */
  Elf32_Half	e_type;			/* Object file type */
  Elf32_Half	e_machine;		/* Architecture */
  Elf32_Word	e_version;		/* Object file version */
  Elf32_Addr	e_entry;		/* Entry point virtual address */
  Elf32_Off	e_phoff;		/* Program header table file offset */
  Elf32_Off	e_shoff;		/* Section header table file offset */
  Elf32_Word	e_flags;		/* Processor-specific flags */
  Elf32_Half	e_ehsize;		/* ELF header size in bytes */
  Elf32_Half	e_phentsize;		/* Program header table entry size */
  Elf32_Half	e_phnum;		/* Program header table entry count */
  Elf32_Half	e_shentsize;		/* Section header table entry size */
  Elf32_Half	e_shnum;		/* Section header table entry count */
  Elf32_Half	e_shstrndx;		/* Section header string table index */
} Elf32_Ehdr;

typedef struct
{
  unsigned char	e_ident[(16)];	/* Magic number and other info */
  Elf64_Half	e_type;			/* Object file type */
  Elf64_Half	e_machine;		/* Architecture */
  Elf64_Word	e_version;		/* Object file version */
  Elf64_Addr	e_entry;		/* Entry point virtual address */
  Elf64_Off	e_phoff;		/* Program header table file offset */
  Elf64_Off	e_shoff;		/* Section header table file offset */
  Elf64_Word	e_flags;		/* Processor-specific flags */
  Elf64_Half	e_ehsize;		/* ELF header size in bytes */
  Elf64_Half	e_phentsize;		/* Program header table entry size */
  Elf64_Half	e_phnum;		/* Program header table entry count */
  Elf64_Half	e_shentsize;		/* Section header table entry size */
  Elf64_Half	e_shnum;		/* Section header table entry count */
  Elf64_Half	e_shstrndx;		/* Section header string table index */
} Elf64_Ehdr;

/* Fields in the e_ident array.  The EI_* macros are indices into the
   array.  The macros under each EI_* macro are the values the byte
   may have.  */













/* Conglomeration of the identification bytes, for easy testing as a word.  */
















					/* Value must be EV_CURRENT */























/* Legal values for e_type (object file type).  */












/* Legal values for e_machine (architecture).  */



















































































/* If it is necessary to assign new unofficial EM_* values, please
   pick large random numbers (0x8523, 0xa7f2, etc.) to minimize the
   chances of collision with official or non-GNU unofficial values.  */




/* Legal values for e_version (version).  */





/* Section header.  */

typedef struct
{
  Elf32_Word	sh_name;		/* Section name (string tbl index) */
  Elf32_Word	sh_type;		/* Section type */
  Elf32_Word	sh_flags;		/* Section flags */
  Elf32_Addr	sh_addr;		/* Section virtual addr at execution */
  Elf32_Off	sh_offset;		/* Section file offset */
  Elf32_Word	sh_size;		/* Section size in bytes */
  Elf32_Word	sh_link;		/* Link to another section */
  Elf32_Word	sh_info;		/* Additional section information */
  Elf32_Word	sh_addralign;		/* Section alignment */
  Elf32_Word	sh_entsize;		/* Entry size if section holds table */
} Elf32_Shdr;

typedef struct
{
  Elf64_Word	sh_name;		/* Section name (string tbl index) */
  Elf64_Word	sh_type;		/* Section type */
  Elf64_Xword	sh_flags;		/* Section flags */
  Elf64_Addr	sh_addr;		/* Section virtual addr at execution */
  Elf64_Off	sh_offset;		/* Section file offset */
  Elf64_Xword	sh_size;		/* Section size in bytes */
  Elf64_Word	sh_link;		/* Link to another section */
  Elf64_Word	sh_info;		/* Additional section information */
  Elf64_Xword	sh_addralign;		/* Section alignment */
  Elf64_Xword	sh_entsize;		/* Entry size if section holds table */
} Elf64_Shdr;

/* Special section indices.  */














/* Legal values for sh_type (section type).  */






































/* Legal values for sh_flags (section flags).  */

















/* Section group handling.  */


/* Symbol table entry.  */

typedef struct
{
  Elf32_Word	st_name;		/* Symbol name (string tbl index) */
  Elf32_Addr	st_value;		/* Symbol value */
  Elf32_Word	st_size;		/* Symbol size */
  unsigned char	st_info;		/* Symbol type and binding */
  unsigned char	st_other;		/* Symbol visibility */
  Elf32_Section	st_shndx;		/* Section index */
} Elf32_Sym;

typedef struct
{
  Elf64_Word	st_name;		/* Symbol name (string tbl index) */
  unsigned char	st_info;		/* Symbol type and binding */
  unsigned char st_other;		/* Symbol visibility */
  Elf64_Section	st_shndx;		/* Section index */
  Elf64_Addr	st_value;		/* Symbol value */
  Elf64_Xword	st_size;		/* Symbol size */
} Elf64_Sym;

/* The syminfo section if available contains additional information about
   every dynamic symbol.  */

typedef struct
{
  Elf32_Half si_boundto;		/* Direct bindings, symbol bound to */
  Elf32_Half si_flags;			/* Per symbol flags */
} Elf32_Syminfo;

typedef struct
{
  Elf64_Half si_boundto;		/* Direct bindings, symbol bound to */
  Elf64_Half si_flags;			/* Per symbol flags */
} Elf64_Syminfo;

/* Possible values for si_boundto.  */




/* Possible bitmasks for si_flags.  */




/* Syminfo version values.  */





/* How to extract and insert information held in the st_info field.  */





/* Both Elf32_Sym and Elf64_Sym use the same one-byte st_info field.  */




/* Legal values for ST_BIND subfield of st_info (symbol binding).  */











/* Legal values for ST_TYPE subfield of st_info (symbol type).  */
















/* Symbol table indices are found in the hash buckets and chain table
   of a symbol hash table section.  This special index value indicates
   the end of a chain, meaning no further symbols are found in that bucket.  */




/* How to extract and insert information held in the st_other field.  */



/* For ELF64 the definitions are the same.  */


/* Symbol visibility specification encoded in the st_other field.  */






/* Relocation table entry without addend (in section of type SHT_REL).  */

typedef struct
{
  Elf32_Addr	r_offset;		/* Address */
  Elf32_Word	r_info;			/* Relocation type and symbol index */
} Elf32_Rel;

/* I have seen two different definitions of the Elf64_Rel and
   Elf64_Rela structures, so we'll leave them out until Novell (or
   whoever) gets their act together.  */
/* The following, at least, is used on Sparc v9, MIPS, and Alpha.  */

typedef struct
{
  Elf64_Addr	r_offset;		/* Address */
  Elf64_Xword	r_info;			/* Relocation type and symbol index */
} Elf64_Rel;

/* Relocation table entry with addend (in section of type SHT_RELA).  */

typedef struct
{
  Elf32_Addr	r_offset;		/* Address */
  Elf32_Word	r_info;			/* Relocation type and symbol index */
  Elf32_Sword	r_addend;		/* Addend */
} Elf32_Rela;

typedef struct
{
  Elf64_Addr	r_offset;		/* Address */
  Elf64_Xword	r_info;			/* Relocation type and symbol index */
  Elf64_Sxword	r_addend;		/* Addend */
} Elf64_Rela;

/* How to extract and insert information held in the r_info field.  */









/* Program segment header.  */

typedef struct
{
  Elf32_Word	p_type;			/* Segment type */
  Elf32_Off	p_offset;		/* Segment file offset */
  Elf32_Addr	p_vaddr;		/* Segment virtual address */
  Elf32_Addr	p_paddr;		/* Segment physical address */
  Elf32_Word	p_filesz;		/* Segment size in file */
  Elf32_Word	p_memsz;		/* Segment size in memory */
  Elf32_Word	p_flags;		/* Segment flags */
  Elf32_Word	p_align;		/* Segment alignment */
} Elf32_Phdr;

typedef struct
{
  Elf64_Word	p_type;			/* Segment type */
  Elf64_Word	p_flags;		/* Segment flags */
  Elf64_Off	p_offset;		/* Segment file offset */
  Elf64_Addr	p_vaddr;		/* Segment virtual address */
  Elf64_Addr	p_paddr;		/* Segment physical address */
  Elf64_Xword	p_filesz;		/* Segment size in file */
  Elf64_Xword	p_memsz;		/* Segment size in memory */
  Elf64_Xword	p_align;		/* Segment alignment */
} Elf64_Phdr;

/* Special value for e_phnum.  This indicates that the real number of
   program headers is too large to fit into e_phnum.  Instead the real
   value is in the field sh_info of section 0.  */



/* Legal values for p_type (segment type).  */






















/* Legal values for p_flags (segment flags).  */







/* Legal values for note segment descriptor types for core files. */





































/* Legal values for the note segment descriptor types for object files.  */




/* Dynamic section entry.  */

typedef struct
{
  Elf32_Sword	d_tag;			/* Dynamic entry type */
  union
    {
      Elf32_Word d_val;			/* Integer value */
      Elf32_Addr d_ptr;			/* Address value */
    } d_un;
} Elf32_Dyn;

typedef struct
{
  Elf64_Sxword	d_tag;			/* Dynamic entry type */
  union
    {
      Elf64_Xword d_val;		/* Integer value */
      Elf64_Addr d_ptr;			/* Address value */
    } d_un;
} Elf64_Dyn;

/* Legal values for d_tag (dynamic entry type).  */










































/* DT_* entries which fall between DT_VALRNGHI & DT_VALRNGLO use the
   Dyn.d_un.d_val field of the Elf*_Dyn structure.  This follows Sun's
   approach.  */
















/* DT_* entries which fall between DT_ADDRRNGHI & DT_ADDRRNGLO use the
   Dyn.d_un.d_ptr field of the Elf*_Dyn structure.

   If any adjustment is made to the ELF object after it has been
   built these entries will need to be adjusted.  */
















/* The versioning entry types.  The next are defined as part of the
   GNU extension.  */





/* These were chosen by Sun.  */








/* Sun added these machine-independent extensions in the "processor-specific"
   range.  Be compatible.  */





/* Values of `d_un.d_val' in the DT_FLAGS entry.  */






/* State flags selectable in the `d_un.d_val' element of the DT_FLAGS_1
   entry in the dynamic section.  */



























/* Flags for the feature selection in DT_FEATURE_1.  */



/* Flags in the DT_POSFLAG_1 entry effecting only the next DT_* entry.  */



/* Version definition sections.  */

typedef struct
{
  Elf32_Half	vd_version;		/* Version revision */
  Elf32_Half	vd_flags;		/* Version information */
  Elf32_Half	vd_ndx;			/* Version Index */
  Elf32_Half	vd_cnt;			/* Number of associated aux entries */
  Elf32_Word	vd_hash;		/* Version name hash value */
  Elf32_Word	vd_aux;			/* Offset in bytes to verdaux array */
  Elf32_Word	vd_next;		/* Offset in bytes to next verdef
					   entry */
} Elf32_Verdef;

typedef struct
{
  Elf64_Half	vd_version;		/* Version revision */
  Elf64_Half	vd_flags;		/* Version information */
  Elf64_Half	vd_ndx;			/* Version Index */
  Elf64_Half	vd_cnt;			/* Number of associated aux entries */
  Elf64_Word	vd_hash;		/* Version name hash value */
  Elf64_Word	vd_aux;			/* Offset in bytes to verdaux array */
  Elf64_Word	vd_next;		/* Offset in bytes to next verdef
					   entry */
} Elf64_Verdef;


/* Legal values for vd_version (version revision).  */




/* Legal values for vd_flags (version information flags).  */



/* Versym symbol index values.  */





/* Auxiliary version information.  */

typedef struct
{
  Elf32_Word	vda_name;		/* Version or dependency names */
  Elf32_Word	vda_next;		/* Offset in bytes to next verdaux
					   entry */
} Elf32_Verdaux;

typedef struct
{
  Elf64_Word	vda_name;		/* Version or dependency names */
  Elf64_Word	vda_next;		/* Offset in bytes to next verdaux
					   entry */
} Elf64_Verdaux;


/* Version dependency section.  */

typedef struct
{
  Elf32_Half	vn_version;		/* Version of structure */
  Elf32_Half	vn_cnt;			/* Number of associated aux entries */
  Elf32_Word	vn_file;		/* Offset of filename for this
					   dependency */
  Elf32_Word	vn_aux;			/* Offset in bytes to vernaux array */
  Elf32_Word	vn_next;		/* Offset in bytes to next verneed
					   entry */
} Elf32_Verneed;

typedef struct
{
  Elf64_Half	vn_version;		/* Version of structure */
  Elf64_Half	vn_cnt;			/* Number of associated aux entries */
  Elf64_Word	vn_file;		/* Offset of filename for this
					   dependency */
  Elf64_Word	vn_aux;			/* Offset in bytes to vernaux array */
  Elf64_Word	vn_next;		/* Offset in bytes to next verneed
					   entry */
} Elf64_Verneed;


/* Legal values for vn_version (version revision).  */




/* Auxiliary needed version information.  */

typedef struct
{
  Elf32_Word	vna_hash;		/* Hash value of dependency name */
  Elf32_Half	vna_flags;		/* Dependency specific information */
  Elf32_Half	vna_other;		/* Unused */
  Elf32_Word	vna_name;		/* Dependency name string offset */
  Elf32_Word	vna_next;		/* Offset in bytes to next vernaux
					   entry */
} Elf32_Vernaux;

typedef struct
{
  Elf64_Word	vna_hash;		/* Hash value of dependency name */
  Elf64_Half	vna_flags;		/* Dependency specific information */
  Elf64_Half	vna_other;		/* Unused */
  Elf64_Word	vna_name;		/* Dependency name string offset */
  Elf64_Word	vna_next;		/* Offset in bytes to next vernaux
					   entry */
} Elf64_Vernaux;


/* Legal values for vna_flags.  */



/* Auxiliary vector.  */

/* This vector is normally only used by the program interpreter.  The
   usual definition in an ABI supplement uses the name auxv_t.  The
   vector is not usually defined in a standard <elf.h> file, but it
   can't hurt.  We rename it to avoid conflicts.  The sizes of these
   types are an arrangement between the exec server and the program
   interpreter, so we don't fully specify them here.  */

typedef struct
{
  uint32_t a_type;		/* Entry type */
  union
    {
      uint32_t a_val;		/* Integer value */
      /* We use to have pointer elements added here.  We cannot do that,
	 though, since it does not work when using 32-bit definitions
	 on 64-bit platforms and vice versa.  */
    } a_un;
} Elf32_auxv_t;

typedef struct
{
  uint64_t a_type;		/* Entry type */
  union
    {
      uint64_t a_val;		/* Integer value */
      /* We use to have pointer elements added here.  We cannot do that,
	 though, since it does not work when using 32-bit definitions
	 on 64-bit platforms and vice versa.  */
    } a_un;
} Elf64_auxv_t;

/* Legal values for a_type (entry type).  */


















/* Some more special a_type values describing the hardware.  */



/* This entry gives some information about the FPU initialization
   performed by the kernel.  */


/* Cache block sizes.  */




/* A special ignored value for PPC, used by the kernel to control the
   interpretation of the AUXV. Must be > 16.  */










/* Pointer to the global system page used for system calls and other
   nice things.  */



/* Shapes of the caches.  Bits 0-3 contains associativity; bits 4-7 contains
   log2 of line size; mask those to get cache size.  */





/* Note section contents.  Each entry in the note section begins with
   a header of a fixed form.  */

typedef struct
{
  Elf32_Word n_namesz;			/* Length of the note's name.  */
  Elf32_Word n_descsz;			/* Length of the note's descriptor.  */
  Elf32_Word n_type;			/* Type of the note.  */
} Elf32_Nhdr;

typedef struct
{
  Elf64_Word n_namesz;			/* Length of the note's name.  */
  Elf64_Word n_descsz;			/* Length of the note's descriptor.  */
  Elf64_Word n_type;			/* Type of the note.  */
} Elf64_Nhdr;

/* Known names of notes.  */

/* Solaris entries in the note section have this name.  */


/* Note entries for GNU systems have this name.  */



/* Defined types of notes for Solaris.  */

/* Value of descriptor (one word) is desired pagesize for the binary.  */



/* Defined note types for GNU systems.  */

/* ABI information.  The descriptor consists of words:
   word 0: OS descriptor
   word 1: major version of the ABI
   word 2: minor version of the ABI
   word 3: subminor version of the ABI
*/



/* Known OSes.  These values can appear in word 0 of an
   NT_GNU_ABI_TAG note section entry.  */





/* Synthetic hwcap information.  The descriptor begins with two words:
   word 0: number of entries
   word 1: bitmask of enabled entries
   Then follow variable-length entries, one byte followed by a
   '\0'-terminated hwcap name string.  The byte gives the bit
   number to test if enabled, (1U << bit) & bitmask.  */


/* Build ID bits as generated by ld --build-id.
   The descriptor consists of any nonzero number of bytes.  */


/* Version note generated by GNU gold containing a version string.  */



/* Move records.  */
typedef struct
{
  Elf32_Xword m_value;		/* Symbol value.  */
  Elf32_Word m_info;		/* Size and index.  */
  Elf32_Word m_poffset;		/* Symbol offset.  */
  Elf32_Half m_repeat;		/* Repeat count.  */
  Elf32_Half m_stride;		/* Stride info.  */
} Elf32_Move;

typedef struct
{
  Elf64_Xword m_value;		/* Symbol value.  */
  Elf64_Xword m_info;		/* Size and index.  */
  Elf64_Xword m_poffset;	/* Symbol offset.  */
  Elf64_Half m_repeat;		/* Repeat count.  */
  Elf64_Half m_stride;		/* Stride info.  */
} Elf64_Move;

/* Macro to construct move records.  */









/* Motorola 68k specific definitions.  */

/* Values for Elf32_Ehdr.e_flags.  */


/* m68k relocs.  */










































/* Keep this the last entry.  */


/* Intel 80386 specific definitions.  */

/* i386 relocs.  */





































/* 38? */





/* Keep this the last entry.  */


/* SUN SPARC specific definitions.  */

/* Legal values for ST_TYPE subfield of st_info (symbol type).  */



/* Values for Elf64_Ehdr.e_flags.  */












/* SPARC relocs.  */


























/* Additional Sparc64 relocs.  */







































































/* Keep this the last entry.  */


/* For Sparc64, legal values for d_tag of Elf64_Dyn.  */




/* MIPS R3000 specific definitions.  */

/* Legal values for e_flags field of Elf32_Ehdr.  */










/* Legal values for MIPS architecture level.  */









/* The following are non-official names and should not be used.  */









/* Special section indices.  */







/* Legal values for sh_type field of Elf32_Shdr.  */









































/* Legal values for sh_flags field of Elf32_Shdr.  */











/* Symbol tables.  */

/* MIPS specific values for `st_other'.  */







/* MIPS specific values for `st_info'.  */


/* Entries found in sections of type SHT_MIPS_GPTAB.  */

typedef union
{
  struct
    {
      Elf32_Word gt_current_g_value;	/* -G value used for compilation */
      Elf32_Word gt_unused;		/* Not used */
    } gt_header;			/* First entry in section */
  struct
    {
      Elf32_Word gt_g_value;		/* If this value were used for -G */
      Elf32_Word gt_bytes;		/* This many bytes would be used */
    } gt_entry;				/* Subsequent entries in section */
} Elf32_gptab;

/* Entry found in sections of type SHT_MIPS_REGINFO.  */

typedef struct
{
  Elf32_Word	ri_gprmask;		/* General registers used */
  Elf32_Word	ri_cprmask[4];		/* Coprocessor registers used */
  Elf32_Sword	ri_gp_value;		/* $gp register value */
} Elf32_RegInfo;

/* Entries found in sections of type SHT_MIPS_OPTIONS.  */

typedef struct
{
  unsigned char kind;		/* Determines interpretation of the
				   variable part of descriptor.  */
  unsigned char size;		/* Size of descriptor, including header.  */
  Elf32_Section section;	/* Section header index of section affected,
				   0 for global options.  */
  Elf32_Word info;		/* Kind-specific information.  */
} Elf_Options;

/* Values for `kind' field in Elf_Options.  */











/* Values for `info' in Elf_Options for ODK_EXCEPTIONS entries.  */















/* Masks for `info' in Elf_Options for an ODK_HWPATCH entry.  */










/* Entry found in `.options' section.  */

typedef struct
{
  Elf32_Word hwp_flags1;	/* Extra flags.  */
  Elf32_Word hwp_flags2;	/* Extra flags.  */
} Elf_Options_Hw;

/* Masks for `info' in ElfOptions for ODK_HWAND and ODK_HWOR entries.  */




/* MIPS relocs.  */





















































/* Keep this the last entry.  */


/* Legal values for p_type field of Elf32_Phdr.  */





/* Special program header types.  */



/* Legal values for d_tag field of Elf32_Dyn.  */












































/* The address of .got.plt in an executable using the new non-PIC ABI.  */

/* The base of the PLT in an executable using the new non-PIC ABI if that
   PLT is writable.  For a non-writable PLT, this is omitted or has a zero
   value.  */



/* Legal values for DT_MIPS_FLAGS Elf32_Dyn entry.  */


















/* Entries found in sections of type SHT_MIPS_LIBLIST.  */

typedef struct
{
  Elf32_Word l_name;		/* Name (string table index) */
  Elf32_Word l_time_stamp;	/* Timestamp */
  Elf32_Word l_checksum;	/* Checksum */
  Elf32_Word l_version;		/* Interface version */
  Elf32_Word l_flags;		/* Flags */
} Elf32_Lib;

typedef struct
{
  Elf64_Word l_name;		/* Name (string table index) */
  Elf64_Word l_time_stamp;	/* Timestamp */
  Elf64_Word l_checksum;	/* Checksum */
  Elf64_Word l_version;		/* Interface version */
  Elf64_Word l_flags;		/* Flags */
} Elf64_Lib;


/* Legal values for l_flags.  */









/* Entries found in sections of type SHT_MIPS_CONFLICT.  */

typedef Elf32_Addr Elf32_Conflict;


/* HPPA specific definitions.  */

/* Legal values for e_flags field of Elf32_Ehdr.  */









/* Defined values for `e_flags & EF_PARISC_ARCH' are:  */





/* Additional section indices.  */




/* Legal values for sh_type field of Elf32_Shdr.  */





/* Legal values for sh_flags field of Elf32_Shdr.  */





/* Legal values for ST_TYPE subfield of st_info (symbol type).  */






/* HPPA relocs.  */
















































































































/* Legal values for p_type field of Elf32_Phdr/Elf64_Phdr.  */




















/* Legal values for p_flags field of Elf32_Phdr/Elf64_Phdr.  */












/* Alpha specific definitions.  */

/* Legal values for e_flags field of Elf64_Ehdr.  */




/* Legal values for sh_type field of Elf64_Shdr.  */

/* These two are primarily concerned with ECOFF debugging info.  */



/* Legal values for sh_flags field of Elf64_Shdr.  */



/* Legal values for st_other field of Elf64_Sym.  */



/* Alpha relocs.  */


































/* Keep this the last entry.  */


/* Magic values of the LITUSE relocation addend.  */







/* Legal values for d_tag of Elf64_Dyn.  */



/* PowerPC specific declarations */

/* Values for Elf32/64_Ehdr.e_flags.  */


/* Cygnus local bits below */



/* PowerPC relocations defined by the ABIs */






































/* PowerPC relocations defined for the TLS access ABI.  */





























/* The remaining relocs are from the Embedded ELF ABI, and are not
   in the SVR4 ELF ABI.  */

















/* Diab tool relocations.  */







/* GNU extension to support local ifunc.  */


/* GNU relocs used in PIC code sequences.  */





/* This is a phony reloc to handle any old fashioned TOC16 references
   that may still be in object files.  */


/* PowerPC specific values for the Dyn d_tag field.  */



/* PowerPC64 relocations defined by the ABIs */





































































/* PowerPC64 relocations defined for the TLS access ABI.  */









































/* GNU extension to support local ifunc.  */







/* PowerPC64 specific values for the Dyn d_tag field.  */






/* ARM specific declarations */

/* Processor specific flags for the ELF header e_flags field.  */

















/* Other constants defined in the ARM ELF spec. version B-01.  */
/* NB. These conflict with values defined above.  */





/* Constants defined in AAELF.  */











/* Additional symbol types for Thumb.  */



/* ARM-specific values for sh_flags */



/* ARM-specific program header flags */




/* Processor specific values for the Phdr p_type field.  */


/* Processor specific values for the Shdr sh_type field.  */





/* AArch64 relocs.  */




























































































































/* Keep this the last entry.  */


/* ARM relocs.  */



































































/* Keep this the last entry.  */


/* TMS320C67xx specific declarations */

/* XXX: no ELF standard yet*/

/* TMS320C67xx relocs. */












/* Keep this the last entry.  */


/* IA-64 specific declarations.  */

/* Processor specific flags for the Ehdr e_flags field.  */




/* Processor specific values for the Phdr p_type field.  */






/* Processor specific flags for the Phdr p_flags field.  */


/* Processor specific values for the Shdr sh_type field.  */



/* Processor specific flags for the Shdr sh_flags field.  */



/* Processor specific values for the Dyn d_tag field.  */



/* IA-64 relocations.  */


















































































/* SH specific declarations */

/* Processor specific flags for the ELF header e_flags field.  */























/* SH relocs.  */





































/* Keep this the last entry.  */


/* S/390 specific definitions.  */

/* Valid values for the e_flags field.  */



/* Additional s390 relocs */































































/* Keep this the last entry.  */



/* CRIS relocations.  */
























/* AMD x86-64 relocations.  */













































/* AM33 relocations.  */






































/* M32R relocs.  */













/* M32R relocs use SHT_RELA.  */


































/* TILEPro relocations.  */
























































/* Relocs 56-59 are currently not defined.  */








































/* TILE-Gx relocations.  */


























































































/* Relocs 90-91 are currently not defined.  */












/* Relocs 104-105 are currently not defined.  */



























/* Indicate the GNU stab.h is in use.  */





enum __stab_debug_code
{
/* Table of DBX symbol codes for the GNU system.
   Copyright (C) 1988, 1997 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public
   License along with the GNU C Library; see the file COPYING.LIB.  If not,
   write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.  */

/* This contains contribution from Cygnus Support.  */

/* Global variable.  Only the name is significant.
   To find the address, look in the corresponding external symbol.  */
N_GSYM= 0x20,

/* Function name for BSD Fortran.  Only the name is significant.
   To find the address, look in the corresponding external symbol.  */
N_FNAME= 0x22,

/* Function name or text-segment variable for C.  Value is its address.
   Desc is supposedly starting line number, but GCC doesn't set it
   and DBX seems not to miss it.  */
N_FUN= 0x24,

/* Data-segment variable with internal linkage.  Value is its address.
   "Static Sym".  */
N_STSYM= 0x26,

/* BSS-segment variable with internal linkage.  Value is its address.  */
N_LCSYM= 0x28,

/* Name of main routine.  Only the name is significant.
   This is not used in C.  */
N_MAIN= 0x2a,

/* Global symbol in Pascal.
   Supposedly the value is its line number; I'm skeptical.  */
N_PC= 0x30,

/* Number of symbols:  0, files,,funcs,lines according to Ultrix V4.0. */
N_NSYMS= 0x32,

/* "No DST map for sym: name, ,0,type,ignored"  according to Ultrix V4.0. */
N_NOMAP= 0x34,

/* New stab from Solaris.  I don't know what it means, but it
   don't seem to contain useful information.  */
N_OBJ= 0x38,

/* New stab from Solaris.  I don't know what it means, but it
   don't seem to contain useful information.  Possibly related to the
   optimization flags used in this module.  */
N_OPT= 0x3c,

/* Register variable.  Value is number of register.  */
N_RSYM= 0x40,

/* Modula-2 compilation unit.  Can someone say what info it contains?  */
N_M2C= 0x42,

/* Line number in text segment.  Desc is the line number;
   value is corresponding address.  */
N_SLINE= 0x44,

/* Similar, for data segment.  */
N_DSLINE= 0x46,

/* Similar, for bss segment.  */
N_BSLINE= 0x48,

/* Sun's source-code browser stabs.  ?? Don't know what the fields are.
   Supposedly the field is "path to associated .cb file".  THIS VALUE
   OVERLAPS WITH N_BSLINE!  */
N_BROWS= 0x48,

/* GNU Modula-2 definition module dependency.  Value is the modification time
   of the definition file.  Other is non-zero if it is imported with the
   GNU M2 keyword %INITIALIZE.  Perhaps N_M2C can be used if there
   are enough empty fields? */
N_DEFD= 0x4a,

/* THE FOLLOWING TWO STAB VALUES CONFLICT.  Happily, one is for Modula-2
   and one is for C++.   Still,... */
/* GNU C++ exception variable.  Name is variable name.  */
N_EHDECL= 0x50,
/* Modula2 info "for imc":  name,,0,0,0  according to Ultrix V4.0.  */
N_MOD2= 0x50,

/* GNU C++ `catch' clause.  Value is its address.  Desc is nonzero if
   this entry is immediately followed by a CAUGHT stab saying what exception
   was caught.  Multiple CAUGHT stabs means that multiple exceptions
   can be caught here.  If Desc is 0, it means all exceptions are caught
   here.  */
N_CATCH= 0x54,

/* Structure or union element.  Value is offset in the structure.  */
N_SSYM= 0x60,

/* Name of main source file.
   Value is starting text address of the compilation.  */
N_SO= 0x64,

/* Automatic variable in the stack.  Value is offset from frame pointer.
   Also used for type descriptions.  */
N_LSYM= 0x80,

/* Beginning of an include file.  Only Sun uses this.
   In an object file, only the name is significant.
   The Sun linker puts data into some of the other fields.  */
N_BINCL= 0x82,

/* Name of sub-source file (#include file).
   Value is starting text address of the compilation.  */
N_SOL= 0x84,

/* Parameter variable.  Value is offset from argument pointer.
   (On most machines the argument pointer is the same as the frame pointer.  */
N_PSYM= 0xa0,

/* End of an include file.  No name.
   This and N_BINCL act as brackets around the file's output.
   In an object file, there is no significant data in this entry.
   The Sun linker puts data into some of the fields.  */
N_EINCL= 0xa2,

/* Alternate entry point.  Value is its address.  */
N_ENTRY= 0xa4,

/* Beginning of lexical block.
   The desc is the nesting level in lexical blocks.
   The value is the address of the start of the text for the block.
   The variables declared inside the block *precede* the N_LBRAC symbol.  */
N_LBRAC= 0xc0,

/* Place holder for deleted include file.  Replaces a N_BINCL and everything
   up to the corresponding N_EINCL.  The Sun linker generates these when
   it finds multiple identical copies of the symbols from an include file.
   This appears only in output from the Sun linker.  */
N_EXCL= 0xc2,

/* Modula-2 scope information.  Can someone say what info it contains?  */
N_SCOPE= 0xc4,

/* End of a lexical block.  Desc matches the N_LBRAC's desc.
   The value is the address of the end of the text for the block.  */
N_RBRAC= 0xe0,

/* Begin named common block.  Only the name is significant.  */
N_BCOMM= 0xe2,

/* End named common block.  Only the name is significant
   (and it should match the N_BCOMM).  */
N_ECOMM= 0xe4,

/* End common (local name): value is address.
   I'm not sure how this is used.  */
N_ECOML= 0xe8,

/* These STAB's are used on Gould systems for Non-Base register symbols
   or something like that.  FIXME.  I have assigned the values at random
   since I don't have a Gould here.  Fixups from Gould folk welcome... */
N_NBTEXT= 0xF0,
N_NBDATA= 0xF2,
N_NBBSS=  0xF4,
N_NBSTS=  0xF6,
N_NBLCS=  0xF8,

/* Second symbol entry containing a length-value for the preceding entry.
   The value is the length.  */
N_LENG= 0xfe,

/* The above information, in matrix format.

			STAB MATRIX
	_________________________________________________
	| 00 - 1F are not dbx stab symbols		|
	| In most cases, the low bit is the EXTernal bit|

	| 00 UNDEF  | 02 ABS	| 04 TEXT   | 06 DATA	|
	| 01  |EXT  | 03  |EXT	| 05  |EXT  | 07  |EXT	|

	| 08 BSS    | 0A INDR	| 0C FN_SEQ | 0E   	|
	| 09  |EXT  | 0B 	| 0D	    | 0F	|

	| 10 	    | 12 COMM	| 14 SETA   | 16 SETT	|
	| 11	    | 13	| 15 	    | 17	|

	| 18 SETD   | 1A SETB	| 1C SETV   | 1E WARNING|
	| 19	    | 1B	| 1D 	    | 1F FN	|

	|_______________________________________________|
	| Debug entries with bit 01 set are unused.	|
	| 20 GSYM   | 22 FNAME	| 24 FUN    | 26 STSYM	|
	| 28 LCSYM  | 2A MAIN	| 2C	    | 2E	|
	| 30 PC	    | 32 NSYMS	| 34 NOMAP  | 36	|
	| 38 OBJ    | 3A	| 3C OPT    | 3E	|
	| 40 RSYM   | 42 M2C	| 44 SLINE  | 46 DSLINE |
	| 48 BSLINE*| 4A DEFD	| 4C        | 4E	|
	| 50 EHDECL*| 52	| 54 CATCH  | 56        |
	| 58        | 5A        | 5C        | 5E	|
	| 60 SSYM   | 62	| 64 SO	    | 66 	|
	| 68 	    | 6A	| 6C	    | 6E	|
	| 70	    | 72	| 74	    | 76	|
	| 78	    | 7A	| 7C	    | 7E	|
	| 80 LSYM   | 82 BINCL	| 84 SOL    | 86	|
	| 88	    | 8A	| 8C	    | 8E	|
	| 90	    | 92	| 94	    | 96	|
	| 98	    | 9A	| 9C	    | 9E	|
	| A0 PSYM   | A2 EINCL	| A4 ENTRY  | A6	|
	| A8	    | AA	| AC	    | AE	|
	| B0	    | B2	| B4	    | B6	|
	| B8	    | BA	| BC	    | BE	|
	| C0 LBRAC  | C2 EXCL	| C4 SCOPE  | C6	|
	| C8	    | CA	| CC	    | CE	|
	| D0	    | D2	| D4	    | D6	|
	| D8	    | DA	| DC	    | DE	|
	| E0 RBRAC  | E2 BCOMM	| E4 ECOMM  | E6	|
	| E8 ECOML  | EA	| EC	    | EE	|
	| F0	    | F2	| F4	    | F6	|
	| F8	    | FA	| FC	    | FE LENG	|
	+-----------------------------------------------+
 * 50 EHDECL is also MOD2.
 * 48 BSLINE is also BROWS.
 */

LAST_UNUSED_STAB_CODE
};






/* -------------------------------------------- */























/* -------------------------------------------- */
/* include the target specific definitions */







/*
 *  x86-64 code generator for TCC
 *
 *  Copyright (c) 2008 Shinichiro Hamaji
 *
 *  Based on i386-gen.c by Fabrice Bellard
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */



/* number of available registers */




/* a register can belong to several classes. The classes must be
   sorted from more general to more precise (see gv2() code which does
   assumptions on it). */























/* pretty names for the registers */
enum {
    TREG_RAX = 0,
    TREG_RCX = 1,
    TREG_RDX = 2,
    TREG_RSP = 4,
    TREG_RSI = 6,
    TREG_RDI = 7,

    TREG_R8  = 8,
    TREG_R9  = 9,
    TREG_R10 = 10,
    TREG_R11 = 11,

    TREG_XMM0 = 16,
    TREG_XMM1 = 17,
    TREG_XMM2 = 18,
    TREG_XMM3 = 19,
    TREG_XMM4 = 20,
    TREG_XMM5 = 21,
    TREG_XMM6 = 22,
    TREG_XMM7 = 23,

    TREG_ST0 = 24,

    TREG_MEM = 0x20
};




/* return registers for function */





/* defined if function parameters must be evaluated in reverse order */


/* pointer size, in bytes */


/* long double size and alignment, in bytes */


/* maximum alignment (for aligned attribute support) */


/******************************************************/

























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































/******************************************************/





/* relocation type for 32 bit data relocation */













































































































































































































































































































/* -------------------------------------------- */
















/* target address type */









/* -------------------------------------------- */












/* token symbol management */
typedef struct TokenSym {
    struct TokenSym *hash_next;
    struct Sym *sym_define; /* direct pointer to define */
    struct Sym *sym_label; /* direct pointer to label */
    struct Sym *sym_struct; /* direct pointer to structure */
    struct Sym *sym_identifier; /* direct pointer to identifier */
    int tok; /* token number */
    int len;
    char str[1];
} TokenSym;




typedef int nwchar_t;


typedef struct CString {
    int size; /* size in bytes */
    void *data; /* either 'char *' or 'nwchar_t *' */
    int size_allocated;
} CString;

/* type definition */
typedef struct CType {
    int t;
    struct Sym *ref;
} CType;

/* constant value */
typedef union CValue {
    long double ld;
    double d;
    float f;
    uint64_t i;
    struct {
        int size;
        const void *data;
    } str;
    int tab[16/4];
} CValue;

/* value on stack */
typedef struct SValue {
    CType type;      /* type */
    unsigned short r;      /* register + flags */
    unsigned short r2;     /* second register, used for 'long long'
                              type. If not used, set to VT_CONST */
    CValue c;              /* constant, if VT_CONST */
    struct Sym *sym;       /* symbol, if (VT_SYM | VT_CONST), or if
    			      result of unary() for an identifier. */
} SValue;

/* symbol attributes */
struct SymAttr {
    unsigned short
    aligned     : 5, /* alignment as log2+1 (0 == unspecified) */
    packed      : 1,
    weak        : 1,
    visibility  : 2,
    dllexport   : 1,
    dllimport   : 1,
    unused      : 5;
};

/* function attributes or temporary attributes for parsing */
struct FuncAttr {
    unsigned
    func_call   : 3, /* calling convention (0..5), see below */
    func_type   : 2, /* FUNC_OLD/NEW/ELLIPSIS */
    func_args   : 8; /* PE __stdcall args */
};

/* GNUC attribute definition */
typedef struct AttributeDef {
    struct SymAttr a;
    struct FuncAttr f;
    struct Section *section;
    int alias_target; /* token */
    int asm_label; /* associated asm label */
    char attr_mode; /* __attribute__((__mode__(...))) */
} AttributeDef;

/* symbol management */
typedef struct Sym {
    int v; /* symbol token */
    unsigned short r; /* associated register or VT_CONST/VT_LOCAL and LVAL type */
    struct SymAttr a; /* symbol attributes */
    union {
        struct {
            int c; /* associated number or Elf symbol index */
            union {
                int sym_scope; /* scope level for locals */
                int jnext; /* next jump label */
                struct FuncAttr f; /* function attributes */
                int auxtype; /* bitfield access type */
            };
        };
        long long enum_val; /* enum constant if IS_ENUM_VAL */
        int *d; /* define token stream */
    };
    CType type; /* associated type */
    union {
        struct Sym *next; /* next related symbol (for fields and anoms) */
        int asm_label; /* associated asm label */
    };
    struct Sym *prev; /* prev symbol in stack */
    struct Sym *prev_tok; /* previous symbol for this token */
} Sym;

/* section definition */
typedef struct Section {
    unsigned long data_offset; /* current data offset */
    unsigned char *data;       /* section data */
    unsigned long data_allocated; /* used for realloc() handling */
    int sh_name;             /* elf section name (only used during output) */
    int sh_num;              /* elf section number */
    int sh_type;             /* elf section type */
    int sh_flags;            /* elf section flags */
    int sh_info;             /* elf section info */
    int sh_addralign;        /* elf section alignment */
    int sh_entsize;          /* elf entry size */
    unsigned long sh_size;   /* section size (only used during output) */
    Elf
    unsigned long sh_offset; /* file offset */
    int nb_hashed_syms;      /* used to resize the hash table */
    struct Section *link;    /* link to another section */
    struct Section *reloc;   /* corresponding section for relocation, if any */
    struct Section *hash;    /* hash table for symbols */
    struct Section *prev;    /* previous section on section stack */
    char name[1];           /* section name */
} Section;

typedef struct DLLReference {
    int level;
    void *handle;
    char name[1];
} DLLReference;

/* -------------------------------------------------- */





/* stored in 'Sym->f.func_type' field */




/* stored in 'Sym->f.func_call' field */







/* field 'Sym.t' for macros */



/* field 'Sym.r' for C labels */




/* type_decl() types */





typedef struct BufferedFile {
    uint8_t *buf_ptr;
    uint8_t *buf_end;
    int fd;
    struct BufferedFile *prev;
    int line_num;    /* current line number - here to simplify code */
    int line_ref;    /* tcc -E: last printed line */
    int ifndef_macro;  /* #ifndef macro / #endif search */
    int ifndef_macro_saved; /* saved ifndef_macro */
    int *ifdef_stack_ptr; /* ifdef_stack value at the start of the file */
    int include_next_index; /* next search path */
    char filename[1024];    /* filename */
    char *true_filename; /* filename not modified by # line directive */
    unsigned char unget[4];
    unsigned char buffer[1]; /* extra size for CH_EOB char */
} BufferedFile;




/* used to record tokens */
typedef struct TokenString {
    int *str;
    int len;
    int lastlen;
    int allocated_len;
    int last_line_num;
    int save_line_num;
    /* used to chain token-strings with begin/end_macro() */
    struct TokenString *prev;
    const int *prev_ptr;
    char alloc;
} TokenString;

/* inline functions */
typedef struct InlineFunc {
    TokenString *func_str;
    Sym *sym;
    char filename[1];
} InlineFunc;

/* include file cache, used to find files faster and also to eliminate
   inclusion if the include file is protected by #ifndef ... #endif */
typedef struct CachedInclude {
    int ifndef_macro;
    int once;
    int hash_next; /* -1 if none */
    char filename[1]; /* path specified in #include */
} CachedInclude;




typedef struct ExprValue {
    uint64_t v;
    Sym *sym;
    int pcrel;
} ExprValue;


typedef struct ASMOperand {
    int id; /* GCC 3 optional identifier (0 if number only supported */
    char *constraint;
    char asm_str[16]; /* computed asm string for operand */
    SValue *vt; /* C value of the expression */
    int ref_index; /* if >= 0, gives reference to a output constraint */
    int input_index; /* if >= 0, gives reference to an input constraint */
    int priority; /* priority, used to assign registers */
    int reg; /* if >= 0, register number used for this operand */
    int is_llong; /* true if double register value */
    int is_memory; /* true if memory operand */
    int is_rw;     /* for '+' modifier */
} ASMOperand;


/* extra symbol attributes (not in symbol table) */
struct sym_attr {
    unsigned got_offset;
    unsigned plt_offset;
    int plt_sym;
    int dyn_index;



};

struct TCCState {

    int verbose; /* if true, display some information during compilation */
    int nostdinc; /* if true, no standard headers are added */
    int nostdlib; /* if true, no standard libraries are added */
    int nocommon; /* if true, do not use common symbols for .bss data */
    int static_link; /* if true, static linking is performed */
    int rdynamic; /* if true, all symbols are exported */
    int symbolic; /* if true, resolve symbols in the current module first */
    int alacarte_link; /* if true, only link in referenced objects from archive */

    char *tcc_lib_path; /* CONFIG_TCCDIR or -B option */
    char *soname; /* as specified on the command line (-soname) */
    char *rpath; /* as specified on the command line (-Wl,-rpath=) */
    int enable_new_dtags; /* ditto, (-Wl,--enable-new-dtags) */

    /* output type, see TCC_OUTPUT_XXX */
    int output_type;
    /* output format, see TCC_OUTPUT_FORMAT_xxx */
    int output_format;

    /* C language options */
    int char_is_unsigned;
    int leading_underscore;
    int ms_extensions;	/* allow nested named struct w/o identifier behave like unnamed */
    int dollars_in_identifiers;	/* allows '$' char in identifiers */
    int ms_bitfields; /* if true, emulate MS algorithm for aligning bitfields */

    /* warning switches */
    int warn_write_strings;
    int warn_unsupported;
    int warn_error;
    int warn_none;
    int warn_implicit_function_declaration;
    int warn_gcc_compat;

    /* compile with debug symbol (and use them if error during execution) */
    int do_debug;







    int run_test; /* nth test to run with -dt -run */

    Elf
    int has_text_addr;

    unsigned section_align; /* section alignment */

    char *init_symbol; /* symbols to call at load-time (not used currently) */
    char *fini_symbol; /* symbols to call at unload-time (not used currently) */





    int nosse; /* For -mno-sse support. */


    /* array of all loaded dlls (including those referenced by loaded dlls) */
    DLLReference **loaded_dlls;
    int nb_loaded_dlls;

    /* include paths */
    char **include_paths;
    int nb_include_paths;

    char **sysinclude_paths;
    int nb_sysinclude_paths;

    /* library paths */
    char **library_paths;
    int nb_library_paths;

    /* crt?.o object path */
    char **crt_paths;
    int nb_crt_paths;

    /* -include files */
    char **cmd_include_files;
    int nb_cmd_include_files;

    /* error handling */
    void *error_opaque;
    void (*error_func)(void *opaque, const char *msg);
    int error_set_jmp_enabled;
    jmp_buf error_jmp_buf;
    int nb_errors;

    /* output file for preprocessing (-E) */
    FILE *ppfp;
    enum {
	LINE_MACRO_OUTPUT_FORMAT_GCC,
	LINE_MACRO_OUTPUT_FORMAT_NONE,
	LINE_MACRO_OUTPUT_FORMAT_STD,
    LINE_MACRO_OUTPUT_FORMAT_P10 = 11
    } Pflag; /* -P switch */
    char dflag; /* -dX value */

    /* for -MD/-MF: collected dependencies for this compilation */
    char **target_deps;
    int nb_target_deps;

    /* compilation */
    BufferedFile *include_stack[32];
    BufferedFile **include_stack_ptr;

    int ifdef_stack[64];
    int *ifdef_stack_ptr;

    /* included files enclosed with #ifndef MACRO */
    int cached_includes_hash[32];
    CachedInclude **cached_includes;
    int nb_cached_includes;

    /* #pragma pack stack */
    int pack_stack[8];
    int *pack_stack_ptr;
    char **pragma_libs;
    int nb_pragma_libs;

    /* inline functions are stored as token lists and compiled last
       only if referenced */
    struct InlineFunc **inline_fns;
    int nb_inline_fns;

    /* sections */
    Section **sections;
    int nb_sections; /* number of sections, including first dummy section */

    Section **priv_sections;
    int nb_priv_sections; /* number of private sections */

    /* got & plt handling */
    Section *got;
    Section *plt;

    /* temporary dynamic symbol sections (for dll loading) */
    Section *dynsymtab_section;
    /* exported dynamic symbol section */
    Section *dynsym;
    /* copy of the global symtab_section variable */
    Section *symtab;
    /* extra attributes (eg. GOT/PLT value) for symtab symbols */
    struct sym_attr *sym_attrs;
    int nb_sym_attrs;





















    /* used by main and tcc_parse_args only */
    struct filespec **files; /* files seen on command line */
    int nb_files; /* number thereof */
    int nb_libraries; /* number of libs thereof */
    int filetype;
    char *outfile; /* output filename */
    int option_r; /* option -r */
    int do_bench; /* option -bench */
    int gen_deps; /* option -MD  */
    char *deps_outfile; /* option -MF */
    int option_pthread; /* -pthread option */
    int argc;
    char **argv;
};

struct filespec {
    char type;
    char alacarte;
    char name[1];
};

/* The current value can be: */

















/* types */

























/* storage */




/* currently unused: 0x000[1248]0000  */














/* type mask (except storage) */



/* symbol was created by tccasm.c first */



/* token values */

/* warning: the following compare tokens depend on i386 asm code */






















/* tokens that carry values (in additional token string space / tokc) --> */















/* <-- */



















/* assignment operators : normal operator or 0x80 */














/* all identifiers and strings have token above that */









/* only used for i386 asm opcodes definitions */







/* number of sizes + 1 */
















enum tcc_token {
    TOK_LAST = 256 - 1

/* keywords */
     ,TOK_INT
     ,TOK_VOID
     ,TOK_CHAR
     ,TOK_IF
     ,TOK_ELSE
     ,TOK_WHILE
     ,TOK_BREAK
     ,TOK_RETURN
     ,TOK_FOR
     ,TOK_EXTERN
     ,TOK_STATIC
     ,TOK_UNSIGNED
     ,TOK_GOTO
     ,TOK_DO
     ,TOK_CONTINUE
     ,TOK_SWITCH
     ,TOK_CASE

     ,TOK_CONST1
     ,TOK_CONST2 /* gcc keyword */
     ,TOK_CONST3 /* gcc keyword */
     ,TOK_VOLATILE1
     ,TOK_VOLATILE2 /* gcc keyword */
     ,TOK_VOLATILE3 /* gcc keyword */
     ,TOK_LONG
     ,TOK_REGISTER
     ,TOK_SIGNED1
     ,TOK_SIGNED2 /* gcc keyword */
     ,TOK_SIGNED3 /* gcc keyword */
     ,TOK_AUTO
     ,TOK_INLINE1
     ,TOK_INLINE2 /* gcc keyword */
     ,TOK_INLINE3 /* gcc keyword */
     ,TOK_RESTRICT1
     ,TOK_RESTRICT2
     ,TOK_RESTRICT3
     ,TOK_EXTENSION /* gcc keyword */

     ,TOK_GENERIC

     ,TOK_FLOAT
     ,TOK_DOUBLE
     ,TOK_BOOL
     ,TOK_SHORT
     ,TOK_STRUCT
     ,TOK_UNION
     ,TOK_TYPEDEF
     ,TOK_DEFAULT
     ,TOK_ENUM
     ,TOK_SIZEOF
     ,TOK_ATTRIBUTE1
     ,TOK_ATTRIBUTE2
     ,TOK_ALIGNOF1
     ,TOK_ALIGNOF2
     ,TOK_TYPEOF1
     ,TOK_TYPEOF2
     ,TOK_TYPEOF3
     ,TOK_LABEL
     ,TOK_ASM1
     ,TOK_ASM2
     ,TOK_ASM3





/*********************************************************************/
/* the following are not keywords. They are included to ease parsing */
/* preprocessor only */
     ,TOK_DEFINE
     ,TOK_INCLUDE
     ,TOK_INCLUDE_NEXT
     ,TOK_IFDEF
     ,TOK_IFNDEF
     ,TOK_ELIF
     ,TOK_ENDIF
     ,TOK_DEFINED
     ,TOK_UNDEF
     ,TOK_ERROR
     ,TOK_WARNING
     ,TOK_LINE
     ,TOK_PRAGMA
     ,TOK___LINE__
     ,TOK___FILE__
     ,TOK___DATE__
     ,TOK___TIME__
     ,TOK___FUNCTION__
     ,TOK___VA_ARGS__
     ,TOK___COUNTER__

/* special identifiers */
     ,TOK___FUNC__

/* special floating point values */
     ,TOK___NAN__
     ,TOK___SNAN__
     ,TOK___INF__

/* attribute identifiers */
/* XXX: handle all tokens generically since speed is not critical */
     ,TOK_SECTION1
     ,TOK_SECTION2
     ,TOK_ALIGNED1
     ,TOK_ALIGNED2
     ,TOK_PACKED1
     ,TOK_PACKED2
     ,TOK_WEAK1
     ,TOK_WEAK2
     ,TOK_ALIAS1
     ,TOK_ALIAS2
     ,TOK_UNUSED1
     ,TOK_UNUSED2
     ,TOK_CDECL1
     ,TOK_CDECL2
     ,TOK_CDECL3
     ,TOK_STDCALL1
     ,TOK_STDCALL2
     ,TOK_STDCALL3
     ,TOK_FASTCALL1
     ,TOK_FASTCALL2
     ,TOK_FASTCALL3
     ,TOK_REGPARM1
     ,TOK_REGPARM2

     ,TOK_MODE
     ,TOK_MODE_QI
     ,TOK_MODE_DI
     ,TOK_MODE_HI
     ,TOK_MODE_SI
     ,TOK_MODE_word

     ,TOK_DLLEXPORT
     ,TOK_DLLIMPORT
     ,TOK_NORETURN1
     ,TOK_NORETURN2
     ,TOK_VISIBILITY1
     ,TOK_VISIBILITY2

     ,TOK_builtin_types_compatible_p
     ,TOK_builtin_choose_expr
     ,TOK_builtin_constant_p
     ,TOK_builtin_frame_address
     ,TOK_builtin_return_address
     ,TOK_builtin_expect
     /*DEF(TOK_builtin_va_list, "__builtin_va_list")*/



     ,TOK_builtin_va_arg_types





/* pragma */
     ,TOK_pack





     ,TOK_comment
     ,TOK_lib
     ,TOK_push_macro
     ,TOK_pop_macro
     ,TOK_once
     ,TOK_option

/* builtin functions or variables */

     ,TOK_memcpy
     ,TOK_memmove
     ,TOK_memset
     ,TOK___divdi3
     ,TOK___moddi3
     ,TOK___udivdi3
     ,TOK___umoddi3
     ,TOK___ashrdi3
     ,TOK___lshrdi3
     ,TOK___ashldi3
     ,TOK___floatundisf
     ,TOK___floatundidf

     ,TOK___floatundixf
     ,TOK___fixunsxfdi

     ,TOK___fixunssfdi
     ,TOK___fixunsdfdi





























































     ,TOK_alloca































/* bound checking symbols */






















/* Tiny Assembler */
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 




 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 
 ,TOK_ASMDIR_ 


/* ------------------------------------------------------------------ */
/* WARNING: relative order of tokens is important. */

/* register */
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 

 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 

 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 


 /* The four low parts of sp/bp/si/di that exist only on
    x86-64 (encoding aliased to ah,ch,dh,dh when not using REX). */
 ,TOK_ASM_ 
 ,TOK_ASM_ 

 /* generic two operands */
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 

 /* unary ops */
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 

  ,TOK_ASM_ 

 /* shifts */
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 

 ,TOK_ASM_ 

 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 

 ,TOK_ASM_ 
 ,TOK_ASM_ 
  ,TOK_ASM_ 

  ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 


  ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 
 ,TOK_ASM_ 

  ,TOK_ASM_ 

  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 

  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 

  ,TOK_ASM_ 

 /* generic FP ops */
  ,TOK_ASM_ 

 ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 

 /* string ops */
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 
  ,TOK_ASM_ 

 /* generic asm ops */







     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 

     /* strings */


















     /* bits */
















     /* prefixes */
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 

     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     
     ,TOK_ASM_ 
     /* NOTE: we took the same order as gas opcode definition order */
/* Right now we can't express the fact that 0xa1/0xa3 can't use $eax and a 
   32 bit moffset as operands.
ALT(DEF_ASM_OP2(movb, 0xa0, 0, OPC_BWLX, OPT_ADDR, OPT_EAX))
ALT(DEF_ASM_OP2(movb, 0xa2, 0, OPC_BWLX, OPT_EAX, OPT_ADDR)) */


/* The moves are special: the 0xb8 form supports IM64 (the only insn that
   does) with REG64.  It doesn't support IM32 with REG64, it would use
   the full movabs form (64bit immediate).  For IM32->REG64 we prefer
   the 0xc7 opcode.  So disallow all 64bit forms and code the rest by hand. */





























































     /* arith */
 /* XXX: use D bit ? */






























     /* shifts */


















    
    




    
    ,TOK_ASM_ 
    ,TOK_ASM_ 

    ,TOK_ASM_ 


    
    
    
    
    
    

     /* float */
     /* specific fcomp handling */
















     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 

     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 
     ,TOK_ASM_ 

    /* fp load */
    
    
    

    
    
    
    
    

    /* fp store */
    
    
    
    

    
    
    
    
    

    
    
    
    
    

    /* exchange */
    ,TOK_ASM_ 

    /* misc FPU */
    
    

    
    
    
    
    ,TOK_ASM_ 

    


    
    
    
    
    
    
    
    
    
    
    
    /* The *q forms of fxrstor/fxsave use a REX prefix.
       If the operand would use extended registers we would have to modify
       it instead of generating a second one.  Currently that's no
       problem with TCC, we don't use extended registers.  */
    
    

    /* segments */
    

    
    
    
    
    
    

    
    
    
    
    
    
    
    


    
    
    

    /* 486 */
    /* bswap can't be applied to 16bit regs */
    
    
    



    

    /* pentium */
    

    /* AMD 64 */
    

    /* pentium pro */


    
    
    
    
    
    
    
    

    
    
    
    

    /* mmx */
    ,TOK_ASM_ 
    /* movd shouldn't accept REG64, but AMD64 spec uses it for 32 and 64 bit
       moves, so let's be compatible. */










    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    

    

    

    

    

    

    

    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /* sse */
    

    

    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
    
    
    
    
    
    
    
    


















      /* must be first OP0 */
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     

     /* strings */






     /* bits */






     /* prefixes */
     
     
     
     
     
     

     
     
     
     
     
     
     

     
     
     ,TOK_ASM_ 

     /* NOTE: we took the same order as gas opcode definition order */
/* Right now we can't express the fact that 0xa1/0xa3 can't use $eax and a 
   32 bit moffset as operands.
ALT(DEF_ASM_OP2(movb, 0xa0, 0, OPC_BWLX, OPT_ADDR, OPT_EAX))
ALT(DEF_ASM_OP2(movb, 0xa2, 0, OPC_BWLX, OPT_EAX, OPT_ADDR)) */
/* The moves are special: the 0xb8 form supports IM64 (the only insn that
   does) with REG64.  It doesn't support IM32 with REG64, it would use
   the full movabs form (64bit immediate).  For IM32->REG64 we prefer
   the 0xc7 opcode.  So disallow all 64bit forms and code the rest by hand. */







     /* arith */





     /* shifts */


    ,TOK_ASM_ 

    
    
    
    
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
     /* float */
     /* specific fcomp handling */
     
     
     
     
     
     
     
     
     
     

     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     

    /* fp load */
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    /* fp store */
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 

    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    /* exchange */
    
    /* misc FPU */
    ,TOK_ASM_ 

    ,TOK_ASM_ 
    ,TOK_ASM_ 
    
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    /* The *q forms of fxrstor/fxsave use a REX prefix.
       If the operand would use extended registers we would have to modify
       it instead of generating a second one.  Currently that's no
       problem with TCC, we don't use extended registers.  */
    ,TOK_ASM_ 

    /* segments */
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 

    /* 486 */
    /* bswap can't be applied to 16bit regs */
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    /* pentium */
    ,TOK_ASM_ 
    /* AMD 64 */
    ,TOK_ASM_ 
    /* pentium pro */
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 

    ,TOK_ASM_ 
    ,TOK_ASM_ 

    /* mmx */
     /* must be last OP0 */
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 

    /* sse */
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 

    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 
    ,TOK_ASM_ 













};

/* keywords: tok >= TOK_IDENT && tok < TOK_UIDENT */


/* ------------ libtcc.c ------------ */

/* use GNU C extensions */
static int gnu_ext;
/* use Tiny C extensions */
static int tcc_ext;
/* XXX: get rid of this ASAP */
static struct TCCState *tcc_state;

/* public functions currently used by the tcc main function */
static char *pstrcpy(char *buf, int buf_size, const char *s);
static char *pstrcat(char *buf, int buf_size, const char *s);
static char *pstrncpy(char *out, const char *in, size_t num);
 char *tcc_basename(const char *name);
 char *tcc_fileextension (const char *name);


 void tcc_free(void *ptr);
 void *tcc_malloc(unsigned long size);
 void *tcc_mallocz(unsigned long size);
 void *tcc_realloc(void *ptr, unsigned long size);
 char *tcc_strdup(const char *str);


















 void tcc_memcheck(void);
 void tcc_error_noabort(const char *fmt, ...);
  void tcc_error(const char *fmt, ...);
 void tcc_warning(const char *fmt, ...);

/* other utilities */
static void dynarray_add(void *ptab, int *nb_ptr, void *data);
static void dynarray_reset(void *pp, int *n);
static  void cstr_ccat(CString *cstr, int ch);
static void cstr_cat(CString *cstr, const char *str, int len);
static void cstr_wccat(CString *cstr, int ch);
static void cstr_new(CString *cstr);
static void cstr_free(CString *cstr);
static void cstr_reset(CString *cstr);

static  void sym_free(Sym *sym);
static Sym *sym_push2(Sym **ps, int v, int t, int c);
static Sym *sym_find2(Sym *s, int v);
static Sym *sym_push(int v, CType *type, int r, int c);
static void sym_pop(Sym **ptop, Sym *b, int keep);
static  Sym *struct_find(int v);
static  Sym *sym_find(int v);
static Sym *global_identifier_push(int v, int t, int c);

static void tcc_open_bf(TCCState *s1, const char *filename, int initlen);
static int tcc_open(TCCState *s1, const char *filename);
static void tcc_close(void);

static int tcc_add_file_internal(TCCState *s1, const char *filename, int flags);
/* flags: */



/* s->filetype: */





/* values from tcc_object_type(...) */






static int tcc_add_crt(TCCState *s, const char *filename);
static int tcc_add_dll(TCCState *s, const char *filename, int flags);
static void tcc_add_pragma_libs(TCCState *s1);
 int tcc_add_library_err(TCCState *s, const char *f);
 void tcc_print_stats(TCCState *s, unsigned total_time);
 int tcc_parse_args(TCCState *s, int *argc, char ***argv, int optind);




/* tcc_parse_args return codes: */









/* ------------ tccpp.c ------------ */

static struct BufferedFile *file;
static int ch, tok;
static CValue tokc;
static const int *macro_ptr;
static int parse_flags;
static int tok_flags;
static CString tokcstr; /* current parsed string, if any */

/* display benchmark infos */
static int total_lines;
static int total_bytes;
static int tok_ident;
static TokenSym **table_ident;














/* isidnum_table flags: */




static TokenSym *tok_alloc(const char *str, int len);
static const char *get_tok_str(int v, CValue *cv);
static void begin_macro(TokenString *str, int alloc);
static void end_macro(void);
static int set_idnum(int c, int val);
static  void tok_str_new(TokenString *s);
static TokenString *tok_str_alloc(void);
static void tok_str_free(TokenString *s);
static void tok_str_free_str(int *str);
static void tok_str_add(TokenString *s, int t);
static void tok_str_add_tok(TokenString *s);
static  void define_push(int v, int macro_type, int *str, Sym *first_arg);
static void define_undef(Sym *s);
static  Sym *define_find(int v);
static void free_defines(Sym *b);
static Sym *label_find(int v);
static Sym *label_push(Sym **ptop, int v, int flags);
static void label_pop(Sym **ptop, Sym *slast, int keep);
static void parse_define(void);
static void preprocess(int is_bof);
static void next_nomacro(void);
static void next(void);
static  void unget_tok(int last_tok);
static void preprocess_start(TCCState *s1, int is_asm);
static void preprocess_end(TCCState *s1);
static void tccpp_new(TCCState *s);
static void tccpp_delete(TCCState *s);
static int tcc_preprocess(TCCState *s1);
static void skip(int c);
static  void expect(const char *msg);

/* space excluding newline */
static  int is_space(int ch) {
    return ch == ' ' || ch == '\t' || ch == '\v' || ch == '\f' || ch == '\r';
}
static  int isid(int c) {
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_';
}
static  int isnum(int c) {
    return c >= '0' && c <= '9';
}
static  int isoct(int c) {
    return c >= '0' && c <= '7';
}
static  int toup(int c) {
    return (c >= 'a' && c <= 'z') ? c - 'a' + 'A' : c;
}

/* ------------ tccgen.c ------------ */


static Sym *sym_free_first;
static void **sym_pools;
static int nb_sym_pools;

static Sym *global_stack;
static Sym *local_stack;
static Sym *local_label_stack;
static Sym *global_label_stack;
static Sym *define_stack;
static CType char_pointer_type, func_old_type, int_type, size_type;
static SValue __vstack[1+/*to make bcheck happy*/ 256], *vtop, *pvtop;

static int rsym, anon_sym, ind, loc;

static int const_wanted; /* true if constant wanted */
static int nocode_wanted; /* true if no code generation wanted for an expression */
static int global_expr;  /* true if compound literals must be allocated globally (used during initializers parsing */
static CType func_vt; /* current function return type (used by return instruction) */
static int func_var; /* true if current function is variadic */
static int func_vc;
static int last_line_num, last_ind, func_ind; /* debug last line number and pc */
static const char *funcname;
static int g_debug;

static void tcc_debug_start(TCCState *s1);
static void tcc_debug_end(TCCState *s1);
static void tcc_debug_funcstart(TCCState *s1, Sym *sym);
static void tcc_debug_funcend(TCCState *s1, int size);
static void tcc_debug_line(TCCState *s1);

static int tccgen_compile(TCCState *s1);
static void free_inline_functions(TCCState *s);
static void check_vstack(void);

static  int is_float(int t);
static int ieee_finite(double d);
static void test_lvalue(void);
static void vpushi(int v);
static Elf
static void update_storage(Sym *sym);
static Sym *external_global_sym(int v, CType *type, int r);
static void vset(CType *type, int r, int v);
static void vswap(void);
static void vpush_global_sym(CType *type, int v);
static void vrote(SValue *e, int n);
static void vrott(int n);
static void vrotb(int n);




static void vpushv(SValue *v);
static void save_reg(int r);
static void save_reg_upstack(int r, int n);
static int get_reg(int rc);
static void save_regs(int n);
static void gaddrof(void);
static int gv(int rc);
static void gv2(int rc1, int rc2);
static void vpop(void);
static void gen_op(int op);
static int type_size(CType *type, int *a);
static void mk_pointer(CType *type);
static void vstore(void);
static void inc(int post, int c);
static void parse_mult_str (CString *astr, const char *msg);
static void parse_asm_str(CString *astr);
static int lvalue_type(int t);
static void indir(void);
static void unary(void);
static void expr_prod(void);
static void expr_sum(void);
static void gexpr(void);
static int expr_const(void);




static int classify_x86_64_va_arg(CType *ty);


/* ------------ tccelf.c ------------ */







typedef struct {
    unsigned int n_strx;         /* index into string table of name */
    unsigned char n_type;         /* type of symbol */
    unsigned char n_other;        /* misc info (usually empty) */
    unsigned short n_desc;        /* description field */
    unsigned int n_value;        /* value of symbol */
} Stab_Sym;

static Section *text_section, *data_section, *bss_section; /* predefined sections */
static Section *common_section;
static Section *cur_text_section; /* current section where function code is generated */

static Section *last_text_section; /* to handle .previous asm directive */







/* symbol sections */
static Section *symtab_section;
/* debug sections */
static Section *stab_section, *stabstr_section;

static void tccelf_new(TCCState *s);
static void tccelf_delete(TCCState *s);
static void tccelf_stab_new(TCCState *s);
static void tccelf_begin_file(TCCState *s1);
static void tccelf_end_file(TCCState *s1);

static Section *new_section(TCCState *s1, const char *name, int sh_type, int sh_flags);
static void section_realloc(Section *sec, unsigned long new_size);
static size_t section_add(Section *sec, Elf
static void *section_ptr_add(Section *sec, Elf
static void section_reserve(Section *sec, unsigned long size);
static Section *find_section(TCCState *s1, const char *name);
static Section *new_symtab(TCCState *s1, const char *symtab_name, int sh_type, int sh_flags, const char *strtab_name, const char *hash_name, int hash_sh_flags);

static void put_extern_sym2(Sym *sym, int sh_num, Elf
static void put_extern_sym(Sym *sym, Section *section, Elf



static void greloca(Section *s, Sym *sym, unsigned long offset, int type, Elf

static int put_elf_str(Section *s, const char *sym);
static int put_elf_sym(Section *s, Elf
static int set_elf_sym(Section *s, Elf
static int find_elf_sym(Section *s, const char *name);
static void put_elf_reloc(Section *symtab, Section *s, unsigned long offset, int type, int symbol);
static void put_elf_reloca(Section *symtab, Section *s, unsigned long offset, int type, int symbol, Elf

static void put_stabs(const char *str, int type, int other, int desc, unsigned long value);
static void put_stabs_r(const char *str, int type, int other, int desc, unsigned long value, Section *sec, int sym_index);
static void put_stabn(int type, int other, int desc, int value);
static void put_stabd(int type, int other, int desc);

static void resolve_common_syms(TCCState *s1);
static void relocate_syms(TCCState *s1, Section *symtab, int do_resolve);
static void relocate_section(TCCState *s1, Section *s);

static int tcc_object_type(int fd, Elf
static int tcc_load_object_file(TCCState *s1, int fd, unsigned long file_offset);
static int tcc_load_archive(TCCState *s1, int fd);
static void tcc_add_bcheck(TCCState *s1);
static void tcc_add_runtime(TCCState *s1);

static void build_got_entries(TCCState *s1);
static struct sym_attr *get_sym_attr(TCCState *s1, int index, int alloc);
static void squeeze_multi_relocs(Section *sec, size_t oldrelocoffset);

static Elf





static int tcc_load_dll(TCCState *s1, int fd, const char *filename, int level);
static int tcc_load_ldscript(TCCState *s1);
static uint8_t *parse_comment(uint8_t *p);
static void minp(void);
static  void inp(void);
static int handle_eob(void);


/* ------------ xxx-link.c ------------ */

/* Whether to generate a GOT/PLT entry and when. NO_GOTPLT_ENTRY is first so
   that unknown relocation don't create a GOT or PLT entry */
enum gotplt_entry {
    NO_GOTPLT_ENTRY,	/* never generate (eg. GLOB_DAT & JMP_SLOT relocs) */
    BUILD_GOT_ONLY,	/* only build GOT (eg. TPOFF relocs) */
    AUTO_GOTPLT_ENTRY,	/* generate if sym is UNDEF */
    ALWAYS_GOTPLT_ENTRY	/* always generate (eg. PLTOFF relocs) */
};

static int code_reloc (int reloc_type);
static int gotplt_entry_type (int reloc_type);
static unsigned create_plt_entry(TCCState *s1, unsigned got_offset, struct sym_attr *attr);
static void relocate_init(Section *sr);
static void relocate(TCCState *s1, Elf
static void relocate_plt(TCCState *s1);

/* ------------ xxx-gen.c ------------ */

static const int reg_classes[25];

static void gsym_addr(int t, int a);
static void gsym(int t);
static void load(int r, SValue *sv);
static void store(int r, SValue *v);
static int gfunc_sret(CType *vt, int variadic, CType *ret, int *align, int *regsize);
static void gfunc_call(int nb_args);
static void gfunc_prolog(CType *func_type);
static void gfunc_epilog(void);
static int gjmp(int t);
static void gjmp_addr(int a);
static int gtst(int inv, int t);

static void gtst_addr(int inv, int a);



static void gen_opi(int op);
static void gen_opf(int op);
static void gen_cvt_ftoi(int t);
static void gen_cvt_ftof(int t);
static void ggoto(void);

static void o(unsigned int c);


static void gen_cvt_itof(int t);

static void gen_vla_sp_save(int addr);
static void gen_vla_sp_restore(int addr);
static void gen_vla_alloc(CType *type, int align);

static  uint16_t read16le(unsigned char *p) {
    return p[0] | (uint16_t)p[1] << 8;
}
static  void write16le(unsigned char *p, uint16_t x) {
    p[0] = x & 255;  p[1] = x >> 8 & 255;
}
static  uint32_t read32le(unsigned char *p) {
  return read16le(p) | (uint32_t)read16le(p + 2) << 16;
}
static  void write32le(unsigned char *p, uint32_t x) {
    write16le(p, x);  write16le(p + 2, x >> 16);
}
static  void add32le(unsigned char *p, int32_t x) {
    write32le(p, read32le(p) + x);
}
static  uint64_t read64le(unsigned char *p) {
  return read32le(p) | (uint64_t)read32le(p + 4) << 32;
}
static  void write64le(unsigned char *p, uint64_t x) {
    write32le(p, x);  write32le(p + 4, x >> 32);
}
static  void add64le(unsigned char *p, int64_t x) {
    write64le(p, read64le(p) + x);
}

/* ------------ i386-gen.c ------------ */

static void g(int c);
static void gen_le16(int c);
static void gen_le32(int c);
static void gen_addr32(int r, Sym *sym, int c);
static void gen_addrpc32(int r, Sym *sym, int c);







/* ------------ x86_64-gen.c ------------ */

static void gen_addr64(int r, Sym *sym, int64_t c);
static void gen_opl(int op);





/* ------------ arm-gen.c ------------ */








/* ------------ arm64-gen.c ------------ */









/* ------------ c67-gen.c ------------ */



/* ------------ tcccoff.c ------------ */






/* ------------ tccasm.c ------------ */
static void asm_instr(void);
static void asm_global_instr(void);

static int find_constraint(ASMOperand *operands, int nb_operands, const char *name, const char **pp);
static Sym* get_asm_sym(int name, Sym *csym);
static void asm_expr(TCCState *s1, ExprValue *pe);
static int asm_int_expr(TCCState *s1);
static int tcc_assemble(TCCState *s1, int do_preprocess);
/* ------------ i386-asm.c ------------ */
static void gen_expr32(ExprValue *pe);

static void gen_expr64(ExprValue *pe);

static void asm_opcode(TCCState *s1, int opcode);
static int asm_parse_regvar(int t);
static void asm_compute_constraints(ASMOperand *operands, int nb_operands, int nb_outputs, const uint8_t *clobber_regs, int *pout_reg);
static void subst_asm_operand(CString *add_str, SValue *sv, int modifier);
static void asm_gen_code(ASMOperand *operands, int nb_operands, int nb_outputs, int is_output, uint8_t *clobber_regs, int out_reg);
static void asm_clobber(uint8_t *clobber_regs, const char *str);


/* ------------ tccpe.c -------------- */


















/* ------------ tccrun.c ----------------- */





















/* ------------ tcctools.c ----------------- */









/********************************************************/






/********************************************************/


int MY_TEST_VT_STATIC = 0x00002000  ;
